package com.apalon.notes.dao;

import android.support.v7.widget.RecyclerView;

import org.greenrobot.greendao.annotation.*;

import java.text.DateFormat;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "NOTE".
 */
@Entity
public class Note {

    @Id(autoincrement = true)
    private Long id;
    private String title;
    private String mainText;
    private Integer background;
    private Boolean created;
    private java.util.Date date;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public Note() {
    }

    public Note(Long id) {
        this.id = id;
    }

    @Generated
    public Note(Long id, String title, String mainText, Integer background, Boolean created, java.util.Date date) {
        this.id = id;
        this.title = title;
        this.mainText = mainText;
        this.background = background;
        this.created = created;
        this.date = date;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getMainText() {
        return mainText;
    }

    public void setMainText(String mainText) {
        this.mainText = mainText;
    }

    public Integer getBackground() {
        return background;
    }

    public void setBackground(Integer background) {
        this.background = background;
    }

    public Boolean getCreated() {
        return created;
    }

    public void setCreated(Boolean created) {
        this.created = created;
    }

    public java.util.Date getDate() {
        return date;
    }

    public void setDate(java.util.Date date) {
        this.date = date;
    }

    // KEEP METHODS - put your custom methods here

    public String getDateToString() {
        return DateFormat.getTimeInstance(DateFormat.SHORT).format(date) + " "
                + DateFormat.getDateInstance(DateFormat.DATE_FIELD).format(date);
    }

    // KEEP METHODS END

}
